# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzurePipeline-conn'
    subscriptionId: 'b27b997e-6e17-4823-b0b6-0d6dd472cf27'
    action: 'Create or Update resource Group'
    resourceGroupName: 'CPF_Test'
    location: 'southeastasia'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/ARMTemplateRepo/CPFAzureDevOpsProject-repo/main/CreateWebApp/template.json'
    overrideParameters: '-projectName CPFAzureDevOpsProject'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
