# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
settings

- task:AzureResourceManagerTemplateDeployment@3
  inputs
    deploymentScope:'Resource Group'
    azureResourceManagerConnection:'AzurePipeline-conn'
    subscriptionId:''
    action:'Create or Update resource Group'
    resourceGroupName:'CPF_Test'
    location:'southeastasia'
    templateLocation:'Url of the file'
    csmFileLink:'https://raw.githubusercontent.com/ARMTemplateRepo/CPFAzureDevOpsProject-repo/main/CreateWebApp/template.json'
    overrideParameter:'-projectName CPFAzureDevOpsProject'
    deploymentMode:'Incremental'
    deployementName:'DeployPipelineTemplate'