# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: 'b27b997e-6e17-4823-b0b6-0d6dd472cf27'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'CPF_Test'
    location: 'Southeast Asia'
    templateLocation: 'URL of the file'
    csmFileLink: 'CreateWebApp/template.json'
    csmParametersFileLink: 'CreateWebApp/parameters.json'
    deploymentMode: 'Incremental'